/* Generated by scripts/release-web.sh. Do not edit by hand. */
window.PAYO_VERSION = {"version": "1.1.0", "date": "2026-09-08", "notes": "Sharper product images from full-resolution captures, embedded demo video, and a link to the new 3D experience."};
(function () {
  var v = window.PAYO_VERSION;
  var el = document.querySelector('[data-version]');
  if (el && v) { el.textContent = 'v' + v.version; el.title = 'Released ' + v.date; }
})();
