/* Generated by scripts/release-web.sh. Do not edit by hand. */
window.PAYO_VERSION = {"version": "1.0.0", "date": "2026-09-08", "notes": "Hackathon release: AI-first landing page, demo trailer, 13-slide deck."};
(function () {
  var v = window.PAYO_VERSION;
  var el = document.querySelector('[data-version]');
  if (el && v) { el.textContent = 'v' + v.version; el.title = 'Released ' + v.date; }
})();
