import { Router } from 'express';
import { handler } from '../lib/handler';
import { requireAuth } from '../middleware/requireAuth';
import { authRoutes } from './authRoutes';
import { actionRoutes } from './actionRoutes';
import { institutionRoutes } from './institutionRoutes';
import { recipientRoutes } from './recipientRoutes';
import { transferRoutes } from './transferRoutes';
import { transactionRoutes } from './transactionRoutes';
import { billRoutes } from './billRoutes';
import { savedBillerRoutes } from './savedBillerRoutes';
import { requestRoutes } from './requestRoutes';
import { pocketRoutes } from './pocketRoutes';
import { cardRoutes } from './cardRoutes';
import { statementRoutes } from './statementRoutes';
import { qrRoutes } from './qrRoutes';
import { chatRoutes } from './chatRoutes';
import { listBillers } from '../controllers/billsController';
import { listTelcos, createRecharge } from '../controllers/rechargesController';
import { me } from '../controllers/authController';
import { updateMe } from '../controllers/meController';
import { getDigest } from '../controllers/digestController';
import { guardianRoutes } from './guardianRoutes';
import { approvalRoutes } from './approvalRoutes';

export const apiRouter = Router();
apiRouter.use('/auth', authRoutes);
apiRouter.get('/me', requireAuth, handler(me));
apiRouter.patch('/me', requireAuth, handler(updateMe));
apiRouter.get('/me/digest', requireAuth, handler(getDigest));
apiRouter.use('/guardian', requireAuth, guardianRoutes);
apiRouter.use('/approvals', requireAuth, approvalRoutes);
apiRouter.use('/actions', requireAuth, actionRoutes);
apiRouter.use('/institutions', requireAuth, institutionRoutes);
apiRouter.use('/recipients', requireAuth, recipientRoutes);
apiRouter.use('/transfers', requireAuth, transferRoutes);
apiRouter.use('/transactions', requireAuth, transactionRoutes);
apiRouter.use('/bills', requireAuth, billRoutes);
apiRouter.use('/saved-billers', requireAuth, savedBillerRoutes);
apiRouter.use('/requests', requireAuth, requestRoutes);
apiRouter.use('/pockets', requireAuth, pocketRoutes);
apiRouter.use('/cards', requireAuth, cardRoutes);
apiRouter.use('/statements', requireAuth, statementRoutes);
apiRouter.use('/qr', requireAuth, qrRoutes);
apiRouter.use('/chat', requireAuth, chatRoutes);
apiRouter.get('/billers', requireAuth, handler(listBillers));
apiRouter.get('/telcos', requireAuth, handler(listTelcos));
apiRouter.post('/recharges', requireAuth, handler(createRecharge));
